version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: cind-node-mongo-redis_mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: testdb
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: cind-node-mongo-redis_redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cind-node-mongo-redis_app
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Połączenie do MongoDB (używamy nazwy serwisu jako hosta)
      MONGO_URI: mongodb://mongo:27017/testdb
      # Połączenie do Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
