name: 'CI/CD Pipeline (Node.js + MongoDB + Redis)'

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Środowisko docelowe (staging/production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  ################################################
  # 1. Faza wstępna (równoległe: lint, audit, format)
  ################################################

  lint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  audit:
    name: Security Audit (npm audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-audit-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-audit-

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (poziom moderate)
        run: npm audit --audit-level=moderate

  format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format

  ################################################################
  # 2. Testy jednostkowe w matrixie (różne wersje Node.js + cache)
  ################################################################

  unit_tests:
    name: Unit Tests (Node.js matrix)
    runs-on: ubuntu-latest
    needs:
      - lint
      - audit
      - format
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      # 1) Instalacja zależności; jeżeli się nie powiedzie, nie przerywamy od razu, ale zapisujemy status.
      - name: Install dependencies
        id: npm_install
        continue-on-error: true
        run: npm ci

      # 2) Wypisanie i upload logów, jeśli instalacja się nie powiodła; potem od razu kończymy joba z błędem.
      - name: Upload npm debug log (jeśli npm ci się nie powiódł)
        if: steps.npm_install.outcome == 'failure'
        run: |
          echo "---- Lista plików w katalogu ~/.npm/_logs ----"
          ls ~/.npm/_logs/ || true
          echo "---- Zawartość wszystkich .log w ~/.npm/_logs ----"
          cat ~/.npm/_logs/*.log || true
        # Opcjonalnie: wrzucamy pliki do artefaktów, żeby można było je pobrać
      - name: Publish npm logs as artifact
        if: steps.npm_install.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs-${{ matrix.node-version }}
          path: ~/.npm/_logs/*.log
      - name: Fail the job if npm ci failed
        if: steps.npm_install.outcome == 'failure'
        run: exit 1

      # 3) Jeżeli npm ci się powiódł, uruchamiamy testy. W przypadku błędu testów natychmiast job się przerwie.
      - name: Run Node.js Unit Tests
        if: steps.npm_install.outcome == 'success'
        run: npm run test:unit

      # 4) Upload coverage tylko jeśli testy przeszły pomyślnie
      - name: Upload unit coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-${{ matrix.node-version }}
          path: coverage/unit

      - name: Publish coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: coverage/unit/**/*.lcov
          flags: unit-${{ matrix.node-version }}

  ###########################################################################
  # 3. Testy uruchamiane we własnym kontenerze Docker (tylko unit-testy)
  ###########################################################################

  container_tests:
    name: Tests in Docker Container (Unit only)
    runs-on: ubuntu-latest
    needs:
      - lint
      - audit
      - format
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image for tests
        run: |
          docker build \
            --tag ci-cd-node-mongo-redis-ci:${{ github.sha }} \
            --file Dockerfile \
            .

      - name: Create local npm cache volume directory
        run: mkdir -p ${{ runner.temp }}/npm-cache

      - name: Run unit tests inside Docker (z ograniczeniami zasobów)
        run: |
          docker run --rm \
            --cpus=2 --memory=4g \
            -v ${{ github.workspace }}:/usr/src/app \
            -v ${{ runner.temp }}/npm-cache:/root/.npm \
            -w /usr/src/app \
            ci-cd-node-mongo-redis-ci:${{ github.sha }} \
            bash -c "npm ci && npm run test:unit"
        # Jeżeli npm ci lub testy w kontenerze się nie powiedzą, job zakończy się od razu błędem.

      - name: Upload Docker-based unit coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: container-unit-coverage
          path: coverage/unit

  ####################################################
  # 4. Testy integracyjne z docker-compose (Mongo+Redis)
  ####################################################

  integration_tests:
    name: Integration Tests (docker-compose Mongo+Redis)
    runs-on: ubuntu-latest
    needs:
      - unit_tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18 # <— Dodajemy Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm # <— Caching npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-18-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18-

      - name: Install dependencies # <— tu faktycznie instalujemy pakiety, w tym jest też "jest"
        run: npm ci

      - name: Setup Docker Compose
        run: docker compose up -d --build

      - name: Wait for App to be healthy
        run: |
          until curl --silent http://localhost:3000/; do
            sleep 1
          done

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Upload integration coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: coverage/integration

  ###########################################
  # 5. Budowanie obrazu produkcyjnego Docker #
  ###########################################

  build:
    name: Build Production Docker Image
    runs-on: ubuntu-latest
    needs:
      - integration_tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ci-cd-node-mongo-redis:${{ github.sha }}

      - name: Save Docker image to tar
        run: docker save ci-cd-node-mongo-redis:${{ github.sha }} -o image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: image.tar

  ##############################################
  # 6. Deployment (symulowany) – tylko na master  #
  ##############################################

  deploy:
    name: Deploy (symulowany)
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/master' && always() }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Symulacja pobrania artefaktu obrazu
        run: echo ">>> [Symulacja deploy] Pobieram artefakt obrazu Docker (tylko echo)."

      - name: Symulacja ładowania obrazu
        run: echo ">>> [Symulacja deploy] Ładuję obraz Docker (tylko echo)."

      - name: Run Custom Deploy Action (symulacja)
        id: custom_deploy
        uses: ./.github/actions/custom-deploy
        with:
          environment: ${{ github.event.inputs.environment || 'staging' }}
          version: ${{ github.sha }}
          notify-team: 'true'

      - name: Wyświetl symulowane informacje o wdrożeniu
        run: |
          echo ">>> [Symulacja deploy] Deployment URL: ${{ steps.custom_deploy.outputs.deployment-url }}"
          echo ">>> [Symulacja deploy] Deployment Time: ${{ steps.custom_deploy.outputs.deployment-time }}"

      - name: Notify on Deployment Failure (tylko symulacja komentarza)
        if: failure()
        run: echo ">>> [Symulacja deploy] Wystąpił błąd w symulowanym wdrożeniu – (tylko echo, brak rzeczywistej akcji)."
